class Historial {
  String id;
  String tipoLicencia;
  String fechaInspeccion;
  String estado;
  String comentario;
  String inspector;
  bool estadoInspeccion; // Renombrar esta propiedad

  Historial(
      {required this.id,
      required this.tipoLicencia,
      required this.fechaInspeccion,
      required this.estado,
      required this.comentario,
      required this.inspector,
      required this.estadoInspeccion // Actualizar el nombre aquí también
      });
}

List<Historial> historialList = [
  Historial(
    id: '001',
    tipoLicencia: 'Comercial',
    fechaInspeccion: '2024/08/01',
    estado: 'Aprobado',
    comentario: 'Todo en orden, licencia renovada.',
    inspector: 'Juan Pérez',
    estadoInspeccion: true,
  ),
  Historial(
    id: '002',
    tipoLicencia: 'Sanitaria',
    fechaInspeccion: '2024/07/15',
    estado: 'Advertencia',
    comentario: 'Faltan documentos, inspección reprogramada.',
    inspector: 'María Gómez',
    estadoInspeccion: false,
  ),
  Historial(
    id: '003',
    tipoLicencia: 'Construcción',
    fechaInspeccion: '2024/06/25',
    estado: 'Rechazado',
    comentario: 'No cumple con las normativas de seguridad.',
    inspector: 'Carlos López',
    estadoInspeccion: false,
  ),
  Historial(
    id: '004',
    tipoLicencia: 'Ambiental',
    fechaInspeccion: '2024/05/10',
    estado: 'Aprobado',
    comentario: 'Se realizaron las adecuaciones necesarias.',
    inspector: 'Ana Fernández',
    estadoInspeccion: true,
  ),
  Historial(
    id: '005',
    tipoLicencia: 'Comercial',
    fechaInspeccion: '2024/04/18',
    estado: 'Aprobado',
    comentario: 'Licencia aprobada sin observaciones.',
    inspector: 'Luis Rodríguez',
    estadoInspeccion: true,
  ),
  Historial(
    id: '006',
    tipoLicencia: 'Transporte',
    fechaInspeccion: '2024/03/22',
    estado: 'Rechazado',
    comentario: 'Vehículos no cumplen con la normativa.',
    inspector: 'José Martínez',
    estadoInspeccion: false,
  ),
  Historial(
    id: '007',
    tipoLicencia: 'Sanitaria',
    fechaInspeccion: '2024/02/14',
    estado: 'Aprobado',
    comentario: 'Cumple con todas las regulaciones.',
    inspector: 'Laura Sánchez',
    estadoInspeccion: true,
  ),
  Historial(
      id: '008',
      tipoLicencia: 'Construcción',
      fechaInspeccion: '2024/01/30',
      estado: 'Advertencia',
      comentario: 'Se requiere inspección adicional.',
      inspector: 'Fernando Gutiérrez',
      estadoInspeccion: true),
  Historial(
      id: '009',
      tipoLicencia: 'Ambiental',
      fechaInspeccion: '2024/01/10',
      estado: 'Aprobado',
      comentario: 'Medidas ambientales implementadas correctamente.',
      inspector: 'Claudia Ramírez',
      estadoInspeccion: true),
  Historial(
      id: '010',
      tipoLicencia: 'Comercial',
      fechaInspeccion: '2023/12/05',
      estado: 'Rechazado',
      comentario: 'Falta de documentación legal.',
      inspector: 'Miguel Torres',
      estadoInspeccion: true),
  Historial(
      id: '011',
      tipoLicencia: 'Comercial',
      fechaInspeccion: '2023/11/20',
      estado: 'Aprobado',
      comentario: 'Revisión satisfactoria, todo en regla.',
      inspector: 'Daniel Herrera',
      estadoInspeccion: true),
  Historial(
      id: '012',
      tipoLicencia: 'Sanitaria',
      fechaInspeccion: '2023/10/15',
      estado: 'Rechazado',
      comentario: 'No cumple con las normas de higiene.',
      inspector: 'Verónica Ruiz',
      estadoInspeccion: true),
  Historial(
      id: '013',
      tipoLicencia: 'Construcción',
      fechaInspeccion: '2023/09/28',
      estado: 'Advertencia',
      comentario: 'Inspección programada para el próximo mes.',
      inspector: 'Andrés Vega',
      estadoInspeccion: true),
  Historial(
      id: '014',
      tipoLicencia: 'Ambiental',
      fechaInspeccion: '2023/08/19',
      estado: 'Aprobado',
      comentario: 'Condiciones ambientales adecuadas.',
      inspector: 'Lucía Morales',
      estadoInspeccion: true),
  Historial(
      id: '015',
      tipoLicencia: 'Transporte',
      fechaInspeccion: '2023/07/12',
      estado: 'Rechazado',
      comentario: 'Vehículos en mal estado, revisión fallida.',
      inspector: 'Diego Ramírez',
      estadoInspeccion: true),
  Historial(
      id: '016',
      tipoLicencia: 'Comercial',
      fechaInspeccion: '2023/06/30',
      estado: 'Aprobado',
      comentario: 'Documentos al día, licencia renovada.',
      inspector: 'Carla Espinoza',
      estadoInspeccion: true),
  Historial(
      id: '017',
      tipoLicencia: 'Sanitaria',
      fechaInspeccion: '2023/05/22',
      estado: 'Advertencia',
      comentario: 'Se solicitó inspección adicional.',
      inspector: 'Ricardo Flores',
      estadoInspeccion: true),
  Historial(
      id: '018',
      tipoLicencia: 'Construcción',
      fechaInspeccion: '2023/04/14',
      estado: 'Aprobado',
      comentario: 'Proyecto aprobado con modificaciones.',
      inspector: 'Elena Vargas',
      estadoInspeccion: true),
  Historial(
      id: '019',
      tipoLicencia: 'Ambiental',
      fechaInspeccion: '2023/03/05',
      estado: 'Rechazado',
      comentario: 'Falta implementar medidas correctivas.',
      inspector: 'Santiago Ortiz',
      estadoInspeccion: false),
  Historial(
      id: '020',
      tipoLicencia: 'Comercial',
      fechaInspeccion: '2023/02/18',
      estado: 'Aprobado',
      comentario: 'Cumple con los requisitos comerciales.',
      inspector: 'Marta Jiménez',
      estadoInspeccion: false),
];
